name: Bug 反馈
description: 提交 Bug 反馈
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        感谢你花时间填写此错误报告！在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 为了保证同样的问题不被重复创建，建议先进行下面的操作。
      options:
        - label: 已经在 [GitHub Issues](https://github.com/Simple-Stark/common-core/issues) 中搜索过该问题
          required: true
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "是什么版本出现了此问题？"
      description: "可以查看对应的pom.xml文件"
  - type: dropdown
    id: database
    validations:
      required: true
    attributes:
      label: "使用的什么数据库？"
      options:
        - MySQL
        - Oracle
        - Other
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: "发生了什么？怎么发生的？"
      description: "最好还告诉我们，你预计会发生什么。"
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
